# Generated by Django 4.2.7 on 2026-08-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gateway.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("deployer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostedApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_deployed", "Not deployed"),
                            ("queued", "Queued"),
                            ("building", "Building"),
                            ("starting", "Starting"),
                            ("live", "Live"),
                            ("paused", "Paused (idle)"),
                            ("stopped", "Stopped"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_deployed",
                        max_length=20,
                    ),
                ),
                (
                    "internal_base_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="http://udom-app-<slug>:<port> — resolvable only inside Docker DNS.",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "container_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "network_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "container_port",
                    models.PositiveIntegerField(
                        default=8000,
                        help_text="Port the app listens on inside its container. Must be >1024 (non-root).",
                    ),
                ),
                ("needs_database", models.BooleanField(default=False)),
                ("db_name", models.CharField(blank=True, default="", max_length=63)),
                ("db_user", models.CharField(blank=True, default="", max_length=63)),
                (
                    "db_password",
                    gateway.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "env_vars",
                    gateway.fields.EncryptedJSONField(
                        blank=True,
                        default=dict,
                        help_text="Admin-supplied environment variables, encrypted at rest.",
                    ),
                ),
                (
                    "admin_dockerfile_override",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A Dockerfile supplied by an admin on the student’s behalf — takes precedence over both a zip-supplied Dockerfile and the runtime template. Cleared by setting to an empty string.",
                    ),
                ),
                ("memory_limit_mb", models.PositiveIntegerField(default=512)),
                ("cpu_limit", models.FloatField(default=0.5)),
                (
                    "last_active_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_app",
                        to="marketplace.application",
                    ),
                ),
                (
                    "runtime_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_apps",
                        to="deployer.runtimetemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hosted App",
                "verbose_name_plural": "Hosted Apps",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AppSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Populated by the gateway proxy once it exists; empty until then.",
                        null=True,
                    ),
                ),
                (
                    "hosted_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="gateway.hostedapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App Session",
                "verbose_name_plural": "App Sessions",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="AllowedHostname",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hosted_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_hostnames",
                        to="gateway.hostedapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allowed Hostname",
                "verbose_name_plural": "Allowed Hostnames",
                "ordering": ["hostname"],
            },
        ),
        migrations.AddIndex(
            model_name="hostedapp",
            index=models.Index(
                fields=["status", "last_active_at"],
                name="gateway_hos_status_dd8886_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appsession",
            index=models.Index(
                fields=["hosted_app", "last_seen_at"],
                name="gateway_app_hosted__98b4e7_idx",
            ),
        ),
    ]
