# Generated by Django 4.2.7 on 2026-08-03 19:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                (
                    "app_file",
                    models.FileField(
                        blank=True,
                        help_text="Uploadable package (APK, IPA, ZIP, etc.). Optional for projects deployed from source_code — a web app hosted by the platform has nothing separate to download.",
                        null=True,
                        upload_to="apps/files/",
                    ),
                ),
                (
                    "source_code",
                    models.FileField(
                        blank=True,
                        help_text="Zipped project source. This is the build input for the deployment pipeline, distinct from app_file which is the distributable package.",
                        null=True,
                        upload_to="projects/source/",
                    ),
                ),
                (
                    "detected_runtime_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-detected runtime key, e.g. 'python-flask', or 'custom' for a project that already ships its own Dockerfile.",
                        max_length=50,
                    ),
                ),
                (
                    "detection_confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("low", "Low"),
                            ("none", "Unrecognized"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "detection_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "needs_dockerfile",
                    models.BooleanField(
                        default=False,
                        help_text="True when the stack was recognized but has no Tier-A template — the student must supply their own Dockerfile.",
                    ),
                ),
                (
                    "deployment_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Developer-written notes for whoever deploys this (build quirks, required env vars, etc.). Shown read-only to the admin.",
                    ),
                ),
                (
                    "demo_credentials",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional login details for reviewers to exercise the running app.",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="apps/icons/"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Set to 0 for a free application.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "min_os_version",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, help_text="File size in bytes."
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of tags.",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier (e.g. Material icon name or Font-Awesome class).",
                        max_length=100,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="apps/screenshots/")),
                ("caption", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="marketplace.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screenshot",
                "verbose_name_plural": "Screenshots",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="marketplace.category",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developed_apps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="True when the reviewer has downloaded the app.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="marketplace.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("app", "user")},
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="marketplace.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Download",
                "verbose_name_plural": "Downloads",
                "ordering": ["-downloaded_at"],
                "indexes": [
                    models.Index(
                        fields=["app", "user"], name="marketplace_app_id_ea0e54_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=50)),
                ("changelog", models.TextField(blank=True, default="")),
                ("app_file", models.FileField(upload_to="apps/versions/")),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="marketplace.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Version",
                "verbose_name_plural": "App Versions",
                "ordering": ["-created_at"],
                "unique_together": {("app", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["status", "is_active"], name="marketplace_status_6673ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["is_featured", "status"], name="marketplace_is_feat_3abb6b_idx"
            ),
        ),
    ]
