# Generated by Django 4.2.7 on 2026-08-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_provision_database",
                    models.BooleanField(
                        blank=True,
                        help_text="Null defers to the runtime template / current HostedApp setting.",
                        null=True,
                    ),
                ),
                (
                    "requested_container_port",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Explicit port override — required when a custom Dockerfile has no EXPOSE instruction.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("building", "Building"),
                            ("starting", "Starting"),
                            ("live", "Live"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("build_log", models.TextField(blank=True, default="")),
                ("image_tag", models.CharField(blank=True, default="", max_length=255)),
                (
                    "container_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("error_summary", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Deployment",
                "verbose_name_plural": "Deployments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuntimeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "dockerfile_template",
                    models.TextField(
                        help_text="Django template string rendered when the project has no Dockerfile."
                    ),
                ),
                ("default_health_path", models.CharField(default="/", max_length=200)),
                (
                    "default_port",
                    models.PositiveIntegerField(
                        default=8000,
                        help_text="Must be >1024: containers run as a non-root user.",
                    ),
                ),
                (
                    "migrate_command",
                    models.CharField(
                        blank=True,
                        help_text="Optional shell command run inside the container after start.",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("needs_database", models.BooleanField(default=False)),
                (
                    "tmpfs_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Paths this runtime must be able to write to at runtime, mounted as tmpfs because the root filesystem is read-only (e.g. Next.js writes .next, Laravel writes storage/). /tmp is always mounted.",
                    ),
                ),
                (
                    "detection_hints",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auto-detection rules. Supports priority, require_files, any_files, require_absent, package_json_deps, content_matches.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Runtime Template",
                "verbose_name_plural": "Runtime Templates",
                "ordering": ["key"],
            },
        ),
    ]
