# Generated by Django 4.2.7 on 2026-08-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="hosted_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployments",
                to="gateway.hostedapp",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="requested_runtime_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit override from the deploy drawer; null means auto-detect.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="deployer.runtimetemplate",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="deployment",
            index=models.Index(
                fields=["hosted_app", "-created_at"],
                name="deployer_de_hosted__0dfc79_idx",
            ),
        ),
    ]
